FROM python:3.6-slim
WORKDIR /app

COPY ./requirements.txt  .

RUN pip install -r requirements.txt
RUN python -m nltk.downloader stopwords
RUN python -m nltk.downloader punkt
RUN python -m nltk.downloader averaged_perceptron_tagger
RUN python -m nltk.downloader wordnet

COPY ./inputs/glove  ./inputs/glove
COPY ./inputs/contractions.json ./inputs/contractions.json
COPY ./models  ./models
COPY ./src ./src 
COPY ./tests ./tests
COPY  gunicorn_config.py app.py  wsgi.py   ./

CMD ["gunicorn", "--config", "gunicorn_config.py", "wsgi:app"]